name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8

    - name: Run Linter
      run: flake8 file_writer/

    - name: Run Tests
      run: pytest tests/

  publish:
    name: Publish to PyPI
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Build Package
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build

    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@v1.10.1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
